# Generated by Django 4.2.1 on 2023-06-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_App', '0002_alter_component_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='platform',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop')], default='desktop', max_length=10),
        ),
    ]
