# Generated by Django 4.2.1 on 2023-06-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_App', '0003_component_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('small', 'Small Laptop'), ('premium', 'Premium Laptop'), ('elite', 'Elite Laptop')], default='small', max_length=10)),
                ('additional_storage_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_additional_storage', to='Eshop_App.component')),
                ('exterior_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_color', to='Eshop_App.component')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_memory', to='Eshop_App.component')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_os', to='Eshop_App.component')),
                ('operating_system_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_os_drive', to='Eshop_App.component')),
            ],
        ),
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('small', 'Small Desktop'), ('premium', 'Premium Desktop'), ('elite', 'Elite Desktop')], default='small', max_length=10)),
                ('extra_case_fans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_case_fans', to='Eshop_App.component')),
                ('graphics_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_graphics', to='Eshop_App.component')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_memory', to='Eshop_App.component')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_motherboard', to='Eshop_App.component')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_os', to='Eshop_App.component')),
                ('power_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_power', to='Eshop_App.component')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_processor', to='Eshop_App.component')),
                ('storage_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_storage', to='Eshop_App.component')),
            ],
        ),
    ]
