# Generated by Django 4.2.1 on 2023-06-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_App', '0006_desktop_price_laptop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='start_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
