# Generated by Django 4.2.1 on 2023-06-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_App', '0007_laptop_start_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='start_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
