# Generated by Django 4.2.2 on 2023-06-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_App', '0008_alter_laptop_start_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=50)),
                ('motherboard', models.CharField(max_length=50)),
                ('graphics_card', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('power_supply', models.CharField(max_length=50)),
                ('extra_case_fans', models.CharField(max_length=50)),
                ('storage_drive', models.CharField(max_length=50)),
                ('operating_system', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='orders/images')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('exterior_color', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('operating_system_drive', models.CharField(max_length=50)),
                ('additional_storage_drive', models.CharField(max_length=50)),
                ('operating_system', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='orders/images')),
            ],
        ),
        migrations.AlterField(
            model_name='component',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='start_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
