# Generated by Django 4.2.1 on 2023-06-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_App', '0012_shippingorder_desktop_shippingorder_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingorder',
            name='desktop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eshop_App.desktop'),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eshop_App.laptop'),
        ),
    ]
